//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cortanarecipes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cortanarecipes.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ingredient.
        /// </summary>
        public static string RsAddIngredient {
            get {
                return ResourceManager.GetString("RsAddIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instruction.
        /// </summary>
        public static string RsAddInstruction {
            get {
                return ResourceManager.GetString("RsAddInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe.
        /// </summary>
        public static string RsAddRecipe {
            get {
                return ResourceManager.GetString("RsAddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        public static string RsCooking {
            get {
                return ResourceManager.GetString("RsCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RsDescription {
            get {
                return ResourceManager.GetString("RsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Detail.
        /// </summary>
        public static string RsIngredientDetail {
            get {
                return ResourceManager.GetString("RsIngredientDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string RsIngredients {
            get {
                return ResourceManager.GetString("RsIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Detail.
        /// </summary>
        public static string RsInstructionDetail {
            get {
                return ResourceManager.GetString("RsInstructionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string RsInstructions {
            get {
                return ResourceManager.GetString("RsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string RsMeasure {
            get {
                return ResourceManager.GetString("RsMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RsName {
            get {
                return ResourceManager.GetString("RsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ingredient.
        /// </summary>
        public static string RsNewIngredient {
            get {
                return ResourceManager.GetString("RsNewIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instruction.
        /// </summary>
        public static string RsNewInstruction {
            get {
                return ResourceManager.GetString("RsNewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        public static string RsNewRecipe {
            get {
                return ResourceManager.GetString("RsNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string RsNote {
            get {
                return ResourceManager.GetString("RsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string RsQty {
            get {
                return ResourceManager.GetString("RsQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string RsQuantity {
            get {
                return ResourceManager.GetString("RsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Detail.
        /// </summary>
        public static string RsRecipeDetail {
            get {
                return ResourceManager.GetString("RsRecipeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RsRecipes {
            get {
                return ResourceManager.GetString("RsRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RsRemove {
            get {
                return ResourceManager.GetString("RsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string RsSave {
            get {
                return ResourceManager.GetString("RsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Speak.
        /// </summary>
        public static string RsSpeakText {
            get {
                return ResourceManager.GetString("RsSpeakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cooking.
        /// </summary>
        public static string RsStartCooking {
            get {
                return ResourceManager.GetString("RsStartCooking", resourceCulture);
            }
        }
    }
}
